name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: dilshan24142
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          svgo_version: 3

      # Deploy to GitHub Pages
      - name: Push to GitHub Pages Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
